/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lorentealberto.byss.ccpf;

import java.io.File;
import javax.swing.JFileChooser;
import lorentealberto.byss.ccpf.filters.RaidoFilter;
import lorentealberto.byss.csimetrico.AlgizFilter;

/**
 *
 * @author Alberto Escribano Lorente
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        keyOptions = new KeyOptions(this, true);
        core = new Core(consola);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simple = new javax.swing.JFileChooser();
        raido = new javax.swing.JFileChooser();
        algiz = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        consola = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cifrar = new javax.swing.JMenuItem();
        descifrar = new javax.swing.JMenuItem();
        firmar = new javax.swing.JMenuItem();
        verificar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        raido.setFileFilter(new RaidoFilter());

        algiz.setFileFilter(new AlgizFilter());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cifrado con Clave Pública y Firma");
        setPreferredSize(new java.awt.Dimension(320, 240));
        setResizable(false);

        consola.setEditable(false);
        consola.setColumns(20);
        consola.setRows(5);
        jScrollPane1.setViewportView(consola);

        jMenu1.setText("Fichero");

        cifrar.setText("Cifrar");
        cifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cifrarActionPerformed(evt);
            }
        });
        jMenu1.add(cifrar);

        descifrar.setText("Descifrar");
        descifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descifrarActionPerformed(evt);
            }
        });
        jMenu1.add(descifrar);

        firmar.setText("Firmar");
        firmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firmarActionPerformed(evt);
            }
        });
        jMenu1.add(firmar);

        verificar.setText("Verificar Firma");
        verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarActionPerformed(evt);
            }
        });
        jMenu1.add(verificar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Claves");

        jMenuItem5.setText("Opciones de Clave");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Generar Claves Nuevas");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Ver Claves Actuales");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        keyOptions.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        core.generarClaves(keyOptions.getCifrado());
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        core.verClavesActuales();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void cifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cifrarActionPerformed
        if (core.clavesGeneradas()) {
            int returnVal = simple.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = simple.getSelectedFile();
                core.cifrar(file, "RSA/ECB/PKCS1Padding");
            }
        } else
            consola.append("\nAntes de cifrar el archivo debes generar"
                    + "\nun par de claves.");
    }//GEN-LAST:event_cifrarActionPerformed

    private void descifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descifrarActionPerformed
        if (core.clavesGeneradas()) {
            int returnVal = algiz.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = algiz.getSelectedFile();
                core.descifrar(file);
            }
        } else
            consola.append("\nAntes de cifrar el archivo debes generar"
                    + "\nun par de claves.");
    }//GEN-LAST:event_descifrarActionPerformed

    private void firmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firmarActionPerformed
        if (core.clavesGeneradas()) {
            int returnVal = simple.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = simple.getSelectedFile();
                core.firmar(file, keyOptions.getFirma());
            }
        } else
            consola.append("\nAntes de firmar el archivo debes generar"
                    + "\nun par de claves.");
            
    }//GEN-LAST:event_firmarActionPerformed

    private void verificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarActionPerformed
        if (core.clavesGeneradas()) {
            int returnVal = raido.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = raido.getSelectedFile();
                core.verificarFirma(file);
            }
        } else
            consola.append("\nAntes de verificar el archivo es necesario"
                    + "\nque exista un llavero");
    }//GEN-LAST:event_verificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    private final KeyOptions keyOptions;
    private final Core core;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser algiz;
    private javax.swing.JMenuItem cifrar;
    private javax.swing.JTextArea consola;
    private javax.swing.JMenuItem descifrar;
    private javax.swing.JMenuItem firmar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFileChooser raido;
    private javax.swing.JFileChooser simple;
    private javax.swing.JMenuItem verificar;
    // End of variables declaration//GEN-END:variables
}
